apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-mini-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-mini-platform
  template:
    metadata:
      labels:
        app: fastapi-mini-platform
    spec:
      containers:
        - name: fastapi-mini-platform
          image: ghcr.io/onetwotwothreeone/cnkl-fastapi-mini-platform:77792278870bd6fe9a926e98ff2fba46c46f266a
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: "0.1.0"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
