apiVersion: v1
kind: Service
metadata:
  name: fastapi-mini-platform-service
spec:
  selector:
    app: fastapi-mini-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
