apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-mini-platform
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: fastapi-mini-platform
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
