resources:
  - ../../base

namespace: cnkl-prod

nameSuffix: -prod

labels:
  - pairs:
      environment: prod
    includeSelectors: true

images:
  - name: ghcr.io/onetwotwothreeone/cnkl-fastapi-mini-platform
    newTag: 2d2dd9c7850342517634879db4123e3106ede24b

patches:
  - path: deployment-patch.yaml
