apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gwan-api-hpa
  namespace: hyean-gwan
  labels:
    app.kubernetes.io/name: gwan-api
    app.kubernetes.io/part-of: hyean
    app.kubernetes.io/component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gwan-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
