apiVersion: v1
kind: Service
metadata:
  name: gwan-api
  namespace: hyean-gwan
  labels:
    app.kubernetes.io/name: gwan-api
    app.kubernetes.io/part-of: hyean
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gwan-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
