apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - gwan-api-rbac.yaml
  - postgres-rbac.yaml
  - postgres-secret.yaml
  - gwan-api-configmap.yaml
  - postgres-pvc.yaml
  - gwan-api-service.yaml
  - postgres-service.yaml
  - gwan-api-deployment.yaml
  - postgres-deployment.yaml
  - gwan-api-hpa.yaml
  - gwan-api-pdb.yaml
  - gwan-api-networkpolicy.yaml
  - postgres-networkpolicy.yaml
