apiVersion: v1
kind: LimitRange
metadata:
  name: hyean-gwan-default-container-limits
  namespace: hyean-gwan
  labels:
    app.kubernetes.io/part-of: hyean
    app.kubernetes.io/component: namespace-policy
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      min:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "1"
        memory: 1Gi
