apiVersion: v1
kind: ServiceAccount
metadata:
  name: gwan-postgres-sa
  namespace: hyean-gwan
  labels:
    app.kubernetes.io/name: gwan-postgres
    app.kubernetes.io/part-of: hyean
    app.kubernetes.io/component: rbac
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gwan-postgres-minimal-role
  namespace: hyean-gwan
  labels:
    app.kubernetes.io/name: gwan-postgres
    app.kubernetes.io/part-of: hyean
    app.kubernetes.io/component: rbac
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gwan-postgres-minimal-rolebinding
  namespace: hyean-gwan
  labels:
    app.kubernetes.io/name: gwan-postgres
    app.kubernetes.io/part-of: hyean
    app.kubernetes.io/component: rbac
subjects:
  - kind: ServiceAccount
    name: gwan-postgres-sa
    namespace: hyean-gwan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gwan-postgres-minimal-role
