apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: hyean-gwan
  labels:
    app.kubernetes.io/name: gwan-postgres
    app.kubernetes.io/part-of: hyean
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gwan-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
