apiVersion: v1
kind: Secret
metadata:
  name: gwan-postgres-secret
  namespace: hyean-gwan
  labels:
    app.kubernetes.io/name: gwan-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: hyean
type: Opaque
stringData:
  POSTGRES_USER: hyean
  POSTGRES_PASSWORD: hyean_password
  POSTGRES_DB: hyean_gwan
