apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: hyean-gwan
  labels:
    app.kubernetes.io/name: gwan-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: hyean
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
