apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: hyean-gwan
  labels:
    app.kubernetes.io/name: gwan-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: hyean
    app.kubernetes.io/managed-by: draft
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: gwan-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
